name: turbostart-npm
description: A simple action to setup node, install npm dependencies, and cache for later use.
branding:
  icon: package
  color: red
runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.1.1
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.0
    - name: Install Dependencies
      shell: bash
      run: npm ci --ignore-scripts
